Repository C-NodeJS/C-Side-BE, pull requests merged in 2022-11, with the labels that each got.

#2 Refactor - Base Project - Remove un-use implementation
  .env
  .prettierrc
  docker-compose.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/app.service.ts
  src/application/app.controller.spec.ts
  src/application/app.controller.ts
  src/application/app.module.ts
  src/application/app.service.ts
  src/application/http-presenters.ts
  src/application/user/dto/create-user.dto.ts
  src/application/user/user.controller.ts
  src/application/user/user.module.ts
  src/application/user/user.service.ts
  src/domain/core/interfaces/input-boundary.ts
  src/domain/core/interfaces/output-boundary.ts
  src/domain/core/interfaces/request.ts
  src/domain/core/interfaces/response.ts
  src/domain/core/interfaces/service.ts
  src/domain/entities/users.ts
  src/domain/usecases/user-create/create-user.request.ts
  src/domain/usecases/user.service.ts
  src/infrastructure/data-access/typeorm/user.entity.ts
  src/main.ts
  test/app.e2e-spec.ts
  yarn.lock
Labels: feature, review request

#3 feat/add role and room entity
  Dockerfile
  docker-compose.yml
  src/application/app.module.ts
  src/application/room/room.module.ts
  src/application/user/user.module.ts
  src/infrastructure/data-access/typeorm/enum.ts
  src/infrastructure/data-access/typeorm/role.entity.ts
  src/infrastructure/data-access/typeorm/room.entity.ts
  src/infrastructure/data-access/typeorm/user.entity.ts
Labels: feature, review request

#7 feature/login: Create Login Function
  .env
  .env.development
  package-lock.json
  package.json
  src/application/app.module.ts
  src/application/auth/auth.controller.ts
  src/application/auth/auth.module.ts
  src/application/auth/auth.service.ts
  src/application/auth/dto/login.dto.ts
  src/application/auth/guards/jwt-auth.guard.ts
  src/application/auth/guards/local-auth.guard.ts
  src/application/auth/strategies/jwt.strategy.ts
  src/application/auth/strategies/local.strategy.ts
  src/application/common/Hash.ts
  src/application/user/user.service.ts
  src/infrastructure/data-access/typeorm/user.entity.ts
  yarn.lock
Labels: feature, review request

#9 fix/feature-login: Login with email
  src/application/auth/auth.service.ts
  src/application/auth/dto/login.dto.ts
  src/application/auth/strategies/local.strategy.ts
  src/application/user/user.service.ts
  src/infrastructure/data-access/typeorm/user.entity.ts
Labels: review request

#10 Feature - Add permission and object entity
  src/application/app.module.ts
  src/application/casl/action.constant.ts
  src/application/casl/casl.module.ts
  src/infrastructure/data-access/typeorm/object.entity.ts
  src/infrastructure/data-access/typeorm/permission.entity.ts
  src/infrastructure/data-access/typeorm/role.entity.ts
  src/infrastructure/data-access/typeorm/room.entity.ts
  src/infrastructure/data-access/typeorm/user.entity.ts
Labels: feature, review request

#4 Feature - Register new user
  package-lock.json
  package.json
  src/application/app.module.ts
  src/application/auth/auth.controller.ts
  src/application/auth/auth.service.ts
  src/application/auth/dto/register.dto.ts
  src/application/common/match.validator.ts
  src/application/common/password.transformer.ts
  src/domain/usecases/user.service.ts
  src/infrastructure/data-access/typeorm/user.entity.ts
  src/main.ts
  yarn.lock
Labels: feature, review request

#11 Sprint1 to Develop
  .env
  .env.development
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  src/application/app.module.ts
  src/application/auth/auth.controller.ts
  src/application/auth/auth.module.ts
  src/application/auth/auth.service.ts
  src/application/auth/dto/login.dto.ts
  src/application/auth/guards/jwt-auth.guard.ts
  src/application/auth/guards/local-auth.guard.ts
  src/application/auth/strategies/jwt.strategy.ts
  src/application/auth/strategies/local.strategy.ts
  src/application/common/Hash.ts
  src/application/room/room.module.ts
  src/application/user/user.module.ts
  src/application/user/user.service.ts
  src/infrastructure/data-access/config/database.ts
  src/infrastructure/data-access/typeorm/enum.ts
  src/infrastructure/data-access/typeorm/role.entity.ts
  src/infrastructure/data-access/typeorm/room.entity.ts
  src/infrastructure/data-access/typeorm/user.entity.ts
  yarn.lock
Labels: feature

#12 Feat - Add permission and init data
  package.json
  src/application/app.controller.ts
  src/application/app.service.ts
  src/application/auth/auth.module.ts
  src/application/auth/guards/ability.guard.ts
  src/application/casl/casl-ability.decorator.ts
  src/application/casl/casl-ability.factory.ts
  src/application/casl/casl.module.ts
  src/application/room/room.module.ts
  src/application/user/user.controller.ts
  src/application/user/user.module.ts
  src/application/user/user.service.ts
  src/infrastructure/data-access/typeorm/permission.entity.ts
  src/infrastructure/data-access/typeorm/role.entity.ts
  yarn.lock
Labels: feature, review request

#15 Fix - Manage rooms
  src/application/room/admin.decorator.ts
  src/application/room/dto/manage_room.dto.ts
  src/application/room/manage_room.service.ts
  src/application/room/room.controller.ts
  src/application/room/room.module.ts
  src/application/room/room.util.ts
  src/application/user/user.service.ts
  src/infrastructure/data-access/config/database.ts
  src/infrastructure/data-access/typeorm/enum.ts
  src/infrastructure/data-access/typeorm/room.entity.ts
  src/infrastructure/data-access/typeorm/user.entity.ts
  src/main.ts
Labels: bug, review request
